version: 2.1

aliases:
  - &restore_gradle_cache
    key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
  - &save_gradle_cache
    key: jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper

attach_workspace: &attach_workspace
  attach_workspace:
    at: app

commands:
  attach_restore_workspace:
    description: Restore the workspace from cache
    steps:
      - checkout
      - *attach_workspace
      - restore_cache: *restore_gradle_cache

config: &config
  working_directory: ~/lazy-otp
  docker:
    - image: circleci/android:api-29
  parallelism: 2
  environment:
    TERM: dumb

jobs:
  checkout_code:
    <<: *config
    steps:
      - checkout
      - restore_cache: *restore_gradle_cache
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - save_cache: *save_gradle_cache

  quality:
    <<: *config
    steps:
      - checkout
      - restore_cache: *restore_gradle_cache
      - run:
          name: Quality checks
          command: ./gradlew lint
      - save_cache: *save_gradle_cache
      - persist_to_workspace:
          root: app
          paths:
            - build/reports/lint-results.xml

  test:
    <<: *config
    steps:
      - checkout
      - restore_cache: *restore_gradle_cache
      - run:
          name: Test
          command: ./gradlew test
      - save_cache: *save_gradle_cache
      - store_test_results:
          path: app/build/test-results

  assemble:
    <<: *config
    steps:
      - attach_restore_workspace
      - run:
          name: Assemble
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/outputs
      - save_cache: *save_gradle_cache
      - persist_to_workspace:
          root: app
          paths:
            - build/outputs/

workflows:
  version: 2
  commit:
    jobs:
      - checkout_code
      - quality:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
      - assemble:
          requires:
            - quality
            - test
          filters:
            branches:
              only:
                - master
                - /release-.*/