name: Build + Check

on:
  push:
    branches:
      - master
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2.1.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3
      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Install dependencies
        run: ./gradlew dependencies --stacktrace --scan
      - name: Quality checks
        run: ./gradlew lint --stacktrace --scan
      - name: Assemble Release
        run: ./gradlew clean assembleRelease --stacktrace --scan

      - name: Archive APKs
        run: |
          .github/script/download_latest_apk latest-release.apk
          mv app/build/outputs/apk/release/*.apk release-${{ github.sha }}.apk
      - name: Upload archived APKs
        uses: actions/upload-artifact@v2.2.1
        with:
          name: apks
          path: '*.apk'
          retention-days: 1

  apk-stats:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Download apks
        uses: actions/download-artifact@v2.0.6
        with:
          name: apks

      - name: Run diffuse
        run: .github/script/diffuse-0.1.0-binary.jar diff latest-release.apk release-${{ github.sha }}.apk > apk-diff-${{ github.sha }}.txt
      - name: Prepare PR comment
        run: printf "\`\`\`\n" > pr-comment.txt && sed '/====   DEX   ====/q' apk-diff-${{ github.sha }}.txt | tac | sed "1,2d" | tac | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' >> pr-comment.txt && echo "\`\`\`"  >> pr-comment.txt
      - name: Comment PR
        uses: machine-learning-apps/pr-comment@1.0.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          path: pr-comment.txt
      - name: Upload full diff
        uses: actions/upload-artifact@v2.2.1
        with:
          name: apk-diffs
          path: apk-diff-${{ github.sha }}.txt
